import type { ThemeColors } from '../colors';

export const generateMapStyle = (colors: ThemeColors) => ({
  version: 8,
  sources: {
    openmaptiles: {
      type: 'vector',
      url: 'https://tiles.openfreemap.org/planet',
    },
  },
  sprite: 'https://tiles.openfreemap.org/sprites/ofm_f384/ofm',
  glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: {
        'background-color': colors.background,
      },
    },
    {
      id: 'landuse_park',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'park',
      paint: {
        'fill-color': colors.landusePark,
        'fill-opacity': 0.6,
      },
    },
    {
      id: 'landuse_residential',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', ['get', 'class'], 'residential'],
      paint: {
        'fill-color': colors.landuseResidential,
        'fill-opacity': 0.5,
      },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      paint: {
        'fill-color': colors.water,
        'fill-opacity': 1,
      },
    },
    {
      id: 'building',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 13,
      paint: {
        'fill-color': colors.building,
        'fill-opacity': 0.9,
        'fill-outline-color': colors.buildingOutline,
      },
    },
    {
      id: 'road_minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
        ['match', ['get', 'class'], ['minor', 'service', 'track'], true, false],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': colors.roadMinor,
        'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 12, 0.5, 15, 2, 18, 8],
      },
    },
    {
      id: 'road_major',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
        ['match', ['get', 'class'], ['primary', 'secondary', 'tertiary'], true, false],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': colors.roadMajor,
        'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 8, 1.2, 15, 5, 18, 12],
      },
    },
    {
      id: 'road_highway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'all',
        ['match', ['geometry-type'], ['LineString', 'MultiLineString'], true, false],
        ['match', ['get', 'brunnel'], ['bridge', 'tunnel'], false, true],
        ['match', ['get', 'class'], ['motorway', 'trunk'], true, false],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': colors.roadHighway,
        'line-width': ['interpolate', ['exponential', 1.5], ['zoom'], 5, 1.5, 15, 7, 18, 16],
      },
    },
    {
      id: 'road_label',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 12,
      filter: [
        'match',
        ['get', 'class'],
        ['motorway', 'trunk', 'primary', 'secondary'],
        true,
        false,
      ],
      layout: {
        'symbol-placement': 'line',
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 12, 10, 14, 12, 18, 14],
        'text-rotation-alignment': 'map',
        'symbol-spacing': 250,
      },
      paint: {
        'text-color': colors.roadLabel,
        'text-halo-color': colors.roadLabelHalo,
        'text-halo-width': 2,
      },
    },
    // Minor road labels (show later)
    {
      id: 'road_label_minor',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 15,
      filter: ['match', ['get', 'class'], ['minor', 'tertiary', 'service'], true, false],
      layout: {
        'symbol-placement': 'line',
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': 10,
        'text-rotation-alignment': 'map',
      },
      paint: {
        'text-color': colors.roadLabel,
        'text-halo-color': colors.roadLabelHalo,
        'text-halo-width': 2,
      },
    },
    {
      id: 'place_label_city',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 8,
      filter: ['==', 'class', 'city'],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 8, 14, 12, 20],
        'text-anchor': 'center',
      },
      paint: {
        'text-color': colors.placeLabelCity,
        'text-halo-color': colors.placeLabelCityHalo,
        'text-halo-width': 2.5,
      },
    },
    {
      id: 'place_label_town',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 10,
      filter: ['match', ['get', 'class'], ['town', 'village'], true, false],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 11, 14, 15],
        'text-anchor': 'center',
      },
      paint: {
        'text-color': colors.placeLabelTown,
        'text-halo-color': colors.placeLabelTownHalo,
        'text-halo-width': 2,
      },
    },
    // POI - Sports venues (stadiums, arenas, sports centers)
    {
      id: 'poi_label_sport',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 14,
      filter: [
        'all',
        ['has', 'name'],
        [
          'match',
          ['get', 'class'],
          ['stadium', 'sports_centre', 'pitch', 'swimming_pool', 'golf_course'],
          true,
          false,
        ],
      ],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 14, 10, 18, 14],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiSport,
        'text-halo-color': colors.poiSportHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Entertainment venues (theaters, cinemas, nightclubs, bars)
    {
      id: 'poi_label_entertainment',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 14,
      filter: [
        'all',
        ['has', 'name'],
        [
          'match',
          ['get', 'class'],
          ['theatre', 'cinema', 'nightclub', 'bar', 'pub', 'casino', 'music'],
          true,
          false,
        ],
      ],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 14, 10, 18, 13],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiEntertainment,
        'text-halo-color': colors.poiEntertainmentHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Cultural venues (museums, galleries, monuments, attractions)
    {
      id: 'poi_label_cultural',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 14,
      filter: [
        'all',
        ['has', 'name'],
        [
          'match',
          ['get', 'class'],
          ['museum', 'gallery', 'arts_centre', 'monument', 'attraction', 'zoo', 'aquarium'],
          true,
          false,
        ],
      ],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 14, 10, 18, 14],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiGeneral,
        'text-halo-color': colors.poiGeneralHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Transportation (metro, bus, train, tram stations)
    {
      id: 'poi_label_transport',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 15,
      filter: [
        'all',
        ['has', 'name'],
        ['match', ['get', 'class'], ['railway', 'bus', 'ferry', 'fuel'], true, false],
      ],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 15, 9, 18, 12],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiTransport,
        'text-halo-color': colors.poiTransportHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Parking
    {
      id: 'poi_label_parking',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 16,
      filter: ['all', ['has', 'name'], ['==', ['get', 'class'], 'parking']],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 16, 9, 18, 11],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiParking,
        'text-halo-color': colors.poiParkingHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Food & Restaurants
    {
      id: 'poi_label_food',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 14,
      filter: [
        'all',
        ['has', 'name'],
        [
          'match',
          ['get', 'class'],
          ['restaurant', 'cafe', 'fast_food', 'food_court', 'ice_cream'],
          true,
          false,
        ],
      ],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 14, 9, 18, 12],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiFood,
        'text-halo-color': colors.poiFoodHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Hotels & Lodging
    {
      id: 'poi_label_lodging',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 15,
      filter: [
        'all',
        ['has', 'name'],
        [
          'match',
          ['get', 'class'],
          ['hotel', 'motel', 'hostel', 'guest_house', 'lodging'],
          true,
          false,
        ],
      ],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 15, 10, 18, 13],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiLodging,
        'text-halo-color': colors.poiLodgingHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Parks & Outdoor spaces (for festivals, outdoor events)
    {
      id: 'poi_label_park',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'park',
      minzoom: 14,
      filter: ['has', 'name'],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Italic'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 14, 10, 18, 14],
        'text-anchor': 'center',
        'text-max-width': 8,
        'text-allow-overlap': false,
      },
      paint: {
        'text-color': colors.poiPark,
        'text-halo-color': colors.poiParkHalo,
        'text-halo-width': 1.5,
      },
    },
    // POI - Education (universities, schools, colleges)
    {
      id: 'poi_label_education',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'poi',
      minzoom: 16,
      filter: [
        'all',
        ['has', 'name'],
        [
          'match',
          ['get', 'class'],
          ['school', 'university', 'college', 'kindergarten', 'library'],
          true,
          false,
        ],
      ],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 16, 10, 18, 14],
        'text-anchor': 'top',
        'text-offset': [0, 0.5],
        'text-max-width': 8,
        'text-allow-overlap': false,
        'symbol-sort-key': ['get', 'rank'],
      },
      paint: {
        'text-color': colors.poiEducation,
        'text-halo-color': colors.poiEducationHalo,
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'boundary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['==', ['get', 'admin_level'], 2],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': colors.border,
        'line-width': ['interpolate', ['linear'], ['zoom'], 0, 0.5, 10, 2],
        'line-opacity': 1,
      },
    },
    {
      id: 'place_label_country',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      maxzoom: 8,
      filter: ['==', ['get', 'class'], 'country'],
      layout: {
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 2, 12, 6, 18],
        'text-anchor': 'center',
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': colors.placeLabelCountry,
        'text-halo-color': colors.placeLabelCountryHalo,
        'text-halo-width': 2.5,
      },
    },
  ],
});
